print("Hello World")
print("welcome")
print("    / |")
print("   /  |")
print("  /   |")
print(" /___ |")
character_name = "Peter"
character_age = "45"
print("There was a man named "+ character_name + ",")
print("He was"+ character_age + "  years Old.")
character_name = "Mike"
print("He really liked the name "+ character_name + ",")
print("but didn't like being "+ character_age + ".")
print("Victor\nPeter")
phrase = "Victor Peter"
print(phrase + " is very handsome and brilliant")
print(phrase.upper().isupper())
print(len(phrase))
print(phrase[0])
print(phrase.index("o"))
print(phrase.replace("Peter", "Peter"))
print(4 + 6)
my_number = 5
print(my_number)
print(str(my_number) + " my favourite number")
My_num = -6.23
print(abs(My_num))
print(pow(24,8))
print(max(4 , 6))
print(min(4 , 6))
print(round(3.7))
from math import *
print(floor(3.8))
print(ceil(3.9))
print(sqrt(244))
name = input("Enter your name:")
age = input("Enter your age:")
print("Hello " + name + " you are " + age)
num1 = input("Enter a number: ")
num2 = input("Enter another number: ")
result = int(num1) + int(num2)
print(result)
num1 = input("Enter a number: ")
num2 = input("Enter another number: ")
result = float(num1) + float(num2)
print(result)
print("welcome Victor")
print("welcome victor")